### ISSUE TITLE
Does not work in Django 3.0

### ISSUE THREAD

**Issue by IntelligentFunction** [RoboAndie/django-countable-field#3]
Not entirely sure why this is here, it does not do what it describes in the gif. The word count appears, but stays at 0 always, defeating the object of telling the user how many characters they have left.

**Comment by RoboAndie** [comment]
You may need to include this tag in your template to render the JavaScript: `{{ form.media }}` (where `form` is the name of your form context variable). Or, if you use the [Crispy Forms](https://github.com/django-crispy-forms/django-crispy-forms) app it will take care of the media element for you. 

Let me know if that works for you. I'll update the instructions if so.
